export enum BookingState {
  INITIATED = 'INITIATED',
  HELD = 'HELD',
  PAID = 'PAID',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  REFUNDED = 'REFUNDED',
}

export enum BookingTrigger {
  HOLD_ACQUIRED = 'HOLD_ACQUIRED',
  REJECTED_BEFORE_HOLD = 'REJECTED_BEFORE_HOLD',
  PAYMENT_CAPTURED = 'PAYMENT_CAPTURED',
  FINALIZATION_SUCCEEDED = 'FINALIZATION_SUCCEEDED',
  FINALIZATION_FAILED = 'FINALIZATION_FAILED',
  HOLD_EXPIRED = 'HOLD_EXPIRED',
  CANCEL_REQUESTED = 'CANCEL_REQUESTED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
}
